server:
  port: 9999
  context-path: /ud
  jsp-servlet:
    init-parameters:
      development: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfw
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-file-size: 100MB
mybatis:
  type-aliases-package: com.baihi.entity
























